// Fill out your copyright notice in the Description page of Project Settings.


#include "Graph/GraphPointAutogenerated.h"


// Sets default values
AGraphPointAutogenerated::AGraphPointAutogenerated()
{
	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
}

// Called when the game starts or when spawned
void AGraphPointAutogenerated::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void AGraphPointAutogenerated::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

