// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Edge.h"
//#include "NameSelectorComponent.h"
//#include "ObjectSerialization.h"
#include "SimEdgeStruct.h"
#include "SimVertexID.h"
#include "GameFramework/Actor.h"
#include "Vertex.h"
#include "GraphSerialized.h"
#include "Components/BoxComponent.h"
#include "GraphAsset.generated.h"


class UGraphDataAsset;
class ULocalGraphRegistry;

USTRUCT()
struct FGraphLayer
{
	GENERATED_BODY()

	FName LayerName;
	TArray<TSharedPtr<Simulation::Vertex>> Vertices;
	TArray<TSharedPtr<Simulation::Edge>> Edges;
};

UCLASS()
class SIMULATIONSYSTEM_API AGraphAsset : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AGraphAsset();

	TWeakPtr<Simulation::Vertex> GetVertex(const FSimVertexID& ID);

	bool LoadGraph();
	bool LoadObjects_Finalize();
	bool LoadObjects_Initial();
	void LoadObjects_Save(); //TODO: Accept SaveObject
	FGraphSerialized SaveObjects();
	void UnloadGraph();

	UFUNCTION(BlueprintPure)
	int GetChunkIndex();
	void SetChunkIndex(int NewChunkIndex);

	UFUNCTION(BlueprintPure)
	FVector GetZoneSize();

	UFUNCTION(BlueprintPure)
	FName GetCurrentLevel();

#if WITH_EDITOR
	UFUNCTION(BlueprintPure)
	bool IsDisableAutogeneratedPoints() const {return bDisableAutogeneratedPoints;}

	UFUNCTION(BlueprintPure)
	bool IsOverrideGlobalGenerationSettings() const {return bOverrideGlobalGenerationSettings;}

	UFUNCTION(BlueprintPure)
	float GetMinEdgeDistance() const {return MinEdgeDistance;}

	UFUNCTION(BlueprintPure)
	float GetMaxEdgeDistance() const {return MaxEdgeDistance;}

	UFUNCTION(BlueprintPure)
	float GetDefaultEdgeDistance() const {return DefaultEdgeDistance;}
	
	void SetGraph(UGraphDataAsset* GraphSerialized);
	TSoftObjectPtr<UGraphDataAsset> GetGraph(){return Graph;}
#endif

	UFUNCTION(BlueprintPure)
	int GetLayersNum(){return ChunkGraphs.Num();}
	
#if WITH_EDITOR
	bool LayerWithNameExists(FName Name);
	FGraphLayer& GetLayerByName(FName Name);
#endif
	
	FVector GetVertexLocationByID(const FSimVertexID& ID);
	FSimVertexID FindClosestVertex(const FVector& Location, int LayerIndex);
	void DrawGraph(FColor Color, float LifeTime, float Thickness);

	UFUNCTION(BlueprintPure)
	ULocalGraphRegistry* GetRegistry(){return Registry;}

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	//UPROPERTY()
	//UNameSelectorComponent* CurrentChunkSelector;

	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	UBoxComponent* SizeBox;

	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FName LevelName;

#if WITH_EDITORONLY_DATA
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	bool bDisableAutogeneratedPoints = false;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	bool bOverrideGlobalGenerationSettings = false;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta=(EditCondition = bOverrideGlobalGenerationSettings))
	float MinEdgeDistance;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta=(EditCondition = bOverrideGlobalGenerationSettings))
	float DefaultEdgeDistance;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta=(EditCondition = bOverrideGlobalGenerationSettings))
	float MaxEdgeDistance;
#endif

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

protected:
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

private:

	UPROPERTY(VisibleAnywhere)
	TSoftObjectPtr<UGraphDataAsset> Graph;
	//FGraphSerialized Graph;

	//UPROPERTY()
	//FProfilesSerialized InitialProfiles;

	UPROPERTY()
	TObjectPtr<ULocalGraphRegistry> Registry;
	
	//USimProfileBase* LoadProfile(FSerializedProfile& Data);

	UPROPERTY()
	int ChunkIndex;

	TArray<FGraphLayer> ChunkGraphs;
	
};
