// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GraphPointBase.h"
#include "SimVertexID.h"
#include "GraphPointAutogenerated.generated.h"

UCLASS()
class SIMULATIONSYSTEMDEVELOPERTOOL_API AGraphPointAutogenerated : public AGraphPointBase
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AGraphPointAutogenerated();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;
};
