// Fill out your copyright notice in the Description page of Project Settings.


#include "SimulationSystemEditorFunctionLibrary.h"

#include "DrawDebugHelpers.h"
#include "EditorLevelLibrary.h"
#include "EditorLevelUtils.h"
//#include "ExposedFunctionLibrary.h"
#include "AssetToolsModule.h"
#include "GlobalGraph.h"
#include "GraphAsset.h"
#include "ProfileComponent.h"
#include "ProfileIDController.h"
#include "SimActorInterface.h"
#include "SimProfileBase.h"
#include "SimulationFunctionLibrary.h"
#include "SimulationSystemDeveloperFunctionLibrary.h"
#include "SimulationSystemDeveloperSettings.h"
#include "Graph/GraphPointManual.h"
#include "Graph/GraphGenerationRestrictor.h"
#include "Graph/GraphPointAutogenerated.h"
#include "Graph/GraphPointLink.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Misc/ScopedSlowTask.h"
#include "SimProfileContainer.h"
#include "EditorSimActor.h"
#include "EditorToolRunHelper.h"
#include "EditorUtilityLibrary.h"
#include "GraphDataAsset.h"
#include "IAssetTools.h"
#include "SimPlayerStart.h"
#include "SimulationSystemSettings.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Factories/DataAssetFactory.h"
#include "Serialization/ObjectAndNameAsStringProxyArchive.h"
#include "Subsystems/EditorActorSubsystem.h"
#include "Subsystems/EditorAssetSubsystem.h"
#include "Subsystems/UnrealEditorSubsystem.h"

void USimulationSystemEditorFunctionLibrary::RebuildSelectedLocalGraph(UWorld* World,
                                                                       AGraphAsset* LocalGraph,
                                                                       const TMap<AGraphPointLink*,
                                                                                  TSharedPtr<Simulation::Vertex>>& Links,
                                                                       FGraphSerialized& ReturnGraph,
                                                                       FProfilesSerialized& ReturnProfiles)
{
	FScopedSlowTask SlowTaskL2(100.0f, NSLOCTEXT("SpawnBuild", "LocalGraphBuild", "Build local graph"));
	SlowTaskL2.MakeDialog();	
	FVector ZoneLocation = LocalGraph->GetActorLocation();
	FVector ZoneSize = LocalGraph->GetZoneSize();
	TArray<FHitResult> OutHits;
	FCollisionQueryParams Params;
	Params.bDebugQuery = true;
	UKismetSystemLibrary::LineTraceMulti(World,
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneSize.Z-ZoneLocation.Z),
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneLocation.Z-ZoneSize.Z),
		UEngineTypes::ConvertToTraceType(GetMutableDefault<USimulationSystemDeveloperSettings>()->SimPointsTraceChannel),
		true, {}, EDrawDebugTrace::Persistent, OutHits, false);
	TArray<FName> Layers = {};
	for(auto& Hit : OutHits)
	{
		Layers.AddUnique(
			GetLayerName(Hit.GetActor())
			);
		SlowTaskL2.EnterProgressFrame(10.0f/OutHits.Num());
	}
	TMap<AGraphPointLink*, TSharedPtr<Simulation::Vertex>> RequiredLinks;
	for(auto& Link : Links)
	{
		if(Link.Key->ConnectsChunk(LocalGraph))
		{
			RequiredLinks.Add(Link);
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Links.Num());
	}
	TArray<AGraphGenerationRestrictor*> Restrictors;
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphGenerationRestrictor::StaticClass(), Actors);
	for(auto& Actor : Actors)
	{
		if(Layers.Contains(GetLayerName(Actor)))
		{
			Restrictors.Add(Cast<AGraphGenerationRestrictor>(Actor));
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Actors.Num());
	}
	TArray<AGraphPointManual*> ManualPoints;
	Actors.Empty();
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointManual::StaticClass(), Actors);
	for(auto& Actor : Actors)
	{
		if(UKismetMathLibrary::IsPointInBox(Actor->GetActorLocation(), ZoneLocation, ZoneSize))
		{
			ManualPoints.Add(Cast<AGraphPointManual>(Actor));
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Actors.Num());
	}
	struct PointsArr
	{
		TArray<FVector> FoundPoints = {};
	};
	TMap<FName, PointsArr> FoundPointsPerLayer;
	TArray<FVector> FoundPointsXY = {};
	//TArray<FVector> ProcessedPoints = {ZoneLocation+FVector(0.0f, 0.0f, 100.0f)};
	TArray<FVector> ProcessedPoints = {ZoneLocation};
	float MinDistanceSq = GetMutableDefault<USimulationSystemDeveloperSettings>()->MinimumDistance
				*GetMutableDefault<USimulationSystemDeveloperSettings>()->MinimumDistance;
	while(ProcessedPoints.Num())
	{
		FScopedSlowTask SlowTaskL3(100.0f, FText::Format(NSLOCTEXT("SpawnBuild", "ProcessPointLocation", "Found points/Locations left: %d/%d"), FoundPointsXY.Num(), ProcessedPoints.Num()));
		SlowTaskL3.MakeDialog();
		FVector Point = ProcessedPoints.Pop();
		if(!UKismetMathLibrary::IsPointInBox(Point, ZoneLocation, ZoneSize))
		{
			continue;
		}
		bool RejectPoint = false;
		for(auto& FoundPoint :FoundPointsXY)
		{
			if(FVector::DistSquared2D(Point, FoundPoint) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		for(auto& SpawnedPoint : ManualPoints)
		{
			if(FVector::DistSquared(Point, SpawnedPoint->GetActorLocation()) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		for(auto& SpawnedPoint : RequiredLinks)
		{
			if(FVector::DistSquared(Point, SpawnedPoint.Key->GetActorLocation()) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		OutHits.Empty();
		World->LineTraceMultiByChannel(
			OutHits,
			FVector(Point.X, Point.Y, ZoneSize.Z-Point.Z),
			FVector(Point.X, Point.Y, Point.Z-ZoneSize.Z),
			
			GetMutableDefault<USimulationSystemDeveloperSettings>()->SimPointsTraceChannel
		);
		FoundPointsXY.Add(FVector(Point.X, Point.Y, 0.0f));
		for(auto& Hit : OutHits)
		{
			FName HitLayer = GetLayerName(Hit.GetActor());
			if(!FoundPointsPerLayer.Contains(HitLayer))
			{
				FoundPointsPerLayer.Add(HitLayer);
			}
			TArray<FVector>& ArrToAdd = FoundPointsPerLayer[HitLayer].FoundPoints;
			for(auto& AlreadyAddedPoint : ArrToAdd)
			{
				if(FVector::DistSquared(Hit.Location, AlreadyAddedPoint) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(!RejectPoint)
			{
				ArrToAdd.Add(Hit.Location+FVector(0.0f, 0.0f, GetMutableDefault<USimulationSystemDeveloperSettings>()->PointZOffset));
			}
		}
		for(int i = 0; i < 6; ++i)
		{
			RejectPoint = false;
			FVector ModifiedPoint = Point
				+UKismetMathLibrary::RotateAngleAxis(
					FVector::ForwardVector,
					i*60.0f,
					FVector::UpVector)
				*GetMutableDefault<USimulationSystemDeveloperSettings>()->DefaultDistance;
			for(auto& AlreadyAddedPoint : FoundPointsXY)
			{
				if(FVector::DistSquared(ModifiedPoint, AlreadyAddedPoint) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			ProcessedPoints.Add(ModifiedPoint);
			//FoundPointsXY.Add(ModifiedPoint);
		}
	}
	SlowTaskL2.EnterProgressFrame(20.0f);
	int Index;
	//using LevelGraph = TPair<TArray<TSharedPtr<Simulation::Vertex>>, TArray<TSharedPtr<Simulation::Edge>>>;
	TArray<FGraphLayer> ChunkGraphs;
	//ChunkGraphs.Reserve(Layers.Num());
	ChunkGraphs.Init(FGraphLayer(), Layers.Num());
	auto EditorActorSubsystem = GEditor->GetEditorSubsystem<UEditorActorSubsystem>();
	if (!ensure(EditorActorSubsystem))
	{
		return;
	}
	for(auto& Pair : FoundPointsPerLayer)
	{
		Index = 0;
		Actors.Empty();
		FScopedSlowTask SlowTaskL3(100.0f, NSLOCTEXT("SpawnBuild", "CreateGraphPoints", "Create graph points"));
		SlowTaskL3.MakeDialog();
		for(auto& Point : Pair.Value.FoundPoints)
		{
			bool RejectPoint = false;
			for(auto& Restrictor : Restrictors)
			{
				if(GetLayerName(Restrictor)==Pair.Key && Restrictor->IsPointInside(Point))
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			for(auto& LinkPoint : RequiredLinks)
			{
				if(FVector::DistSquared(Point, LinkPoint.Key->GetActorLocation()) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			FSimVertexID NewID;
			NewID.ChunkID = LocalGraph->GetChunkIndex();
			ensure(Layers.Contains(Pair.Key));
			if (Layers.Contains(Pair.Key))
			{
				NewID.LevelID = Layers.Find(Pair.Key);
				NewID.VertexID = Index++;
				auto GraphPoint = Cast<AGraphPointAutogenerated>(EditorActorSubsystem->SpawnActorFromClass(AGraphPointAutogenerated::StaticClass(), Point));
				GraphPoint->SetVertexID(NewID);
				GraphPoint->SetFolderPath(TEXT("Autogenerated/GraphPoints"));
				Actors.Add(GraphPoint);
				auto& Arr = ChunkGraphs[NewID.LevelID].Vertices;
				Arr.Add(MakeShared<Simulation::Vertex>(NewID, Point));
				SlowTaskL3.EnterProgressFrame(100.0f/Pair.Value.FoundPoints.Num());
			}
		}
		UEditorLevelUtils::MoveActorsToLevel(Actors, UGameplayStatics::GetStreamingLevel(World, Pair.Key));
		SlowTaskL2.EnterProgressFrame(10.0f/FoundPointsPerLayer.Num());
	}
	float MaxDistance = GetMutableDefault<USimulationSystemDeveloperSettings>()->MaximumDistance;
	for(int i = 0; i < Layers.Num(); ++i)
	{
		auto& ChunkVertices = ChunkGraphs[i].Vertices;
		auto& ChunkEdges = ChunkGraphs[i].Edges;
		FScopedSlowTask SlowTaskL3(ChunkVertices.Num(), FText::Format(NSLOCTEXT("SpawnBuild", "ProcessEdgeCreation", "Process vertices from layer {0}"), FText::FromName(Layers[i])));
		SlowTaskL3.MakeDialog();
		for(int L1 = 0; L1 < ChunkVertices.Num(); ++L1)
		{
			for(int L2 = L1+1; L2 < ChunkVertices.Num(); ++L2)
			{
				auto& VertexOne = ChunkVertices[L1];
				auto& VertexTwo = ChunkVertices[L2];
				if(FVector::DistSquared(VertexOne->GetLocation(), VertexTwo->GetLocation()) > MaxDistance*MaxDistance)
				{
					continue;
				}
				ChunkEdges.Add(MakeShared<Simulation::Edge>(VertexOne, VertexTwo));
				VertexOne->AddEdge(ChunkEdges.Last());
				VertexTwo->AddEdge(ChunkEdges.Last());
			}
			SlowTaskL3.EnterProgressFrame(1);
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Layers.Num());
	}
	{
		FScopedSlowTask SlowTaskL3(RequiredLinks.Num(), NSLOCTEXT("SpawnBuild", "ProcessEdgeCreation", "Process link vertices"));
		SlowTaskL3.MakeDialog();
		for(auto& LinkPoint : RequiredLinks)
		{
			auto& LinkVertex = LinkPoint.Value;
			for(int i = 0; i < Layers.Num(); ++i)
			{
				const auto& ChunkVertices = ChunkGraphs[i].Vertices;
				auto& ChunkEdges = ChunkGraphs[i].Edges;
				for(auto& Vertex : ChunkVertices)
				{
					if(FVector::DistSquared(Vertex->GetLocation(), LinkVertex->GetLocation()) > MaxDistance*MaxDistance)
					{
						continue;
					}
					ChunkEdges.Add(MakeShared<Simulation::Edge>(Vertex, LinkVertex));
					Vertex->AddEdge(ChunkEdges.Last());
					LinkVertex->AddEdge(ChunkEdges.Last());
				}
			}
			SlowTaskL3.EnterProgressFrame(1);
		}
		SlowTaskL2.EnterProgressFrame(5.0f);
	}
	{
		auto Num = ChunkGraphs.Num();
		FScopedSlowTask SlowTaskL3(Num, NSLOCTEXT("SpawnBuild", "GraphSerialization", "Serialize Graph"));
		SlowTaskL3.MakeDialog();
		ReturnGraph.Layers.SetNumZeroed(Num);
		//for (const auto& ChunkLayer : ChunkGraphs)
		for (int32 i = 0; i < Num; ++i)
		{
			const auto& ChunkLayer = ChunkGraphs[i];
			auto& SerializedLayer = ReturnGraph.Layers[i];
			SerializedLayer.LayerName = Layers[i];
			for (const auto& ChunkVertex : ChunkLayer.Vertices)
			{
				SerializedLayer.Vertices.Add(ChunkVertex->GetVertexID(), ChunkVertex->GetLocation());
			}
			for (const auto& ChunkEdge : ChunkLayer.Edges)
			{
				SerializedLayer.Edges.Add(
					{
						ChunkEdge.Get()->GetVertexOne().Pin()->GetVertexID(),
						ChunkEdge.Get()->GetVertexTwo().Pin()->GetVertexID()
					});
			}
			SlowTaskL3.EnterProgressFrame(1);
		}
		SlowTaskL2.EnterProgressFrame(5.0f);
	}

	{
		auto GlobalGraph = USimulationFunctionLibrary::GetGlobalGraph(World);
		if (ensure(GlobalGraph)
			&& ensure(GlobalGraph->LoadGraphLinks())
			&& ensure(LocalGraph->LoadGraph()))
		{
			RebuildLocalGraphSpawn(World, LocalGraph, ReturnProfiles);
		}
		LocalGraph->UnloadGraph();
		GlobalGraph->UnloadGraphLinks();
	}
	
	SlowTaskL2.EnterProgressFrame(10.0f);
}

void USimulationSystemEditorFunctionLibrary::RebuildLocalGraphSpawn(UWorld* World, AGraphAsset* LocalGraph,
	FProfilesSerialized& ReturnProfiles)
{
	TArray<AActor*> Actors;
	TSet<AActor*> ActorsInsideChunk = {};
	UGameplayStatics::GetAllActorsWithInterface(World, USimActorInterface::StaticClass(), Actors);
	for(auto& Actor: Actors)
	{
		if(UKismetMathLibrary::IsPointInBox(Actor->GetActorLocation(), LocalGraph->GetActorLocation(), LocalGraph->GetZoneSize()))
		{
			ActorsInsideChunk.Add(Actor);
		}
	}
	for(auto& Actor : ActorsInsideChunk)
	{
		FName LayerName = GetLayerName(Actor);
		if (!ensure(LocalGraph->LayerWithNameExists(LayerName)))
		{
			continue;
		}
		auto& Layer = LocalGraph->GetLayerByName(LayerName);
		FEditorScriptExecutionGuard ScriptGuard;
		if (ISimActorInterface::Execute_UseInSimulation(Actor))
		{
			auto Component = ISimActorInterface::Execute_GetProfileComponent(Actor);
			if (!IsValid(Component))
			{
				ISimActorInterface::Execute_DirectSetGraphVertex(
					Actor, GetClosestVertex(Actor->GetActorLocation(), Layer).Pin()->GetVertexID());
			} else
			{
				Component->InitProfile(ReturnProfiles,
									   GetClosestVertex(Actor->GetActorLocation(), Layer).Pin()->
									   GetVertexID());
			}
		}
	}
}

FName USimulationSystemEditorFunctionLibrary::GetLayerName(UObject* Obj)
{
	FString Str;
	if(auto GraphPoint = Cast<AGraphPointLink>(Obj))
	{
		Str = GraphPoint->GetChunkName();
	} else
	{
		Str = UKismetSystemLibrary::GetObjectName(
			UKismetSystemLibrary::GetOuterObject(
				UKismetSystemLibrary::GetOuterObject(
					Obj
					)
				)
			);
	}
	return FName(Str);
}

bool USimulationSystemEditorFunctionLibrary::IsUniqueTriple(
	const TArray<TTuple<TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>>>& Trilpes,
	TTuple<TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>> NewTuple)
{
	for(auto& Triple : Trilpes)
	{
		TSet<TWeakPtr<Simulation::Edge>> EdgesSet = {};
		EdgesSet.Add(Triple.Get<0>());
		EdgesSet.Add(Triple.Get<1>());
		EdgesSet.Add(Triple.Get<2>());
		EdgesSet.Add(NewTuple.Get<0>());
		EdgesSet.Add(NewTuple.Get<1>());
		EdgesSet.Add(NewTuple.Get<2>());
		if(EdgesSet.Num() <=3)
		{
			return false;
		}
	}
	return true;
}

TWeakPtr<Simulation::Vertex> USimulationSystemEditorFunctionLibrary::GetClosestVertex(FVector Location, 
	const TArray<FGraphLayer>& GraphPart, int LayerIndex)
{
	if (!GraphPart.IsValidIndex(LayerIndex))
	{
		return nullptr;
	}
	return GetClosestVertex(Location, GraphPart[LayerIndex]);
}

TWeakPtr<Simulation::Vertex> USimulationSystemEditorFunctionLibrary::GetClosestVertex(FVector Location,
	const FGraphLayer& GraphLayer)
{
	TWeakPtr<Simulation::Vertex> ClosestVertex = GraphLayer.Vertices[0];
	long double ClosestDistanceSq = FVector::DistSquared(Location, ClosestVertex.Pin()->GetLocation());
	bool FoundCloser;
	do
	{
		FoundCloser = false;
		auto NewCloser = ClosestVertex;
		for(auto& Edge : ClosestVertex.Pin()->GetEdges())
		{
			auto Opposite = Edge.Pin()->GetOpposite(ClosestVertex);
			float OppositeDistanceSq = FVector::DistSquared(Opposite.Pin()->GetLocation(), Location);
			if(OppositeDistanceSq < ClosestDistanceSq)
			{
				FoundCloser = true;
				ClosestDistanceSq = OppositeDistanceSq;
				NewCloser = Opposite;
			}
		}
		ClosestVertex = NewCloser;
	} while (FoundCloser);
	return ClosestVertex;
}

void USimulationSystemEditorFunctionLibrary::SaveProfile(USimProfileBase* Profile, FProfilesSerialized& ReturnProfiles,
                                                         FSimVertexID VertexID)
{
	auto Data = ReturnProfiles.AddLast();
	Data.GetElem().GlobalParent = &ReturnProfiles;
	Profile->NativeSave(VertexID, Data);
}

void USimulationSystemEditorFunctionLibrary::CleanUp()
{
	FScopedSlowTask SlowTaskL1(100.0f, NSLOCTEXT("SpawnBuild", "Clean Up", "Clean up spawn data"));
	SlowTaskL1.MakeDialog();
	auto EditorActorSubsystem = GEditor->GetEditorSubsystem<UEditorActorSubsystem>();
	auto UnrealEditorSubsystem = GEditor->GetEditorSubsystem<UUnrealEditorSubsystem>();
	if (!ensure(EditorActorSubsystem) || !ensure(UnrealEditorSubsystem))
	{
		return;
	}
	auto World = UnrealEditorSubsystem->GetEditorWorld();
	auto GlobalGraph = USimulationFunctionLibrary::GetGlobalGraph(World);
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointAutogenerated::StaticClass(), Actors);
	ensure(EditorActorSubsystem->DestroyActors(Actors));
	Actors.Empty();
	GlobalGraph->ResetVertices();
	GlobalGraph->GetProfileIDsController()->ClearAllProfiles();
	GEngine->ForceGarbageCollection(true);
}

void USimulationSystemEditorFunctionLibrary::Build()
{
	FScopedSlowTask SlowTaskL1(100.0f, NSLOCTEXT("SpawnBuild", "BuilddAll", "Full spawn building"));
	SlowTaskL1.MakeDialog();
	auto UnrealEditorSubsystem = GEditor->GetEditorSubsystem<UUnrealEditorSubsystem>();
	if (!ensure(UnrealEditorSubsystem))
	{
		return;
	}
	auto World = UnrealEditorSubsystem->GetEditorWorld();
	auto GlobalGraph = USimulationFunctionLibrary::GetGlobalGraph(World);
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointLink::StaticClass(), Actors);
	
	TMap<AGraphPointLink*, TSharedPtr<Simulation::Vertex>> Links;
	for(uint16 i = 0; i < Actors.Num(); ++i)
	{
		auto CastedActor = Cast<AGraphPointLink>(Actors[i]);
		const auto& Vertex =  Links.Add(CastedActor, MakeShared<Simulation::Vertex>(FSimVertexID{0, 0, i}, CastedActor->GetActorLocation()));
		GlobalGraph->AddVertex(Vertex->GetVertexID(), Vertex->GetLocation());
		SlowTaskL1.EnterProgressFrame(10.0f/Actors.Num());
	}
	ensure(GlobalGraph->MarkPackageDirty());
	Actors.Empty();
	UGameplayStatics::GetAllActorsOfClass(World, AGraphAsset::StaticClass(), Actors);
	GlobalGraph->SetChunks(Actors);
	for(int i = 0; i < Actors.Num(); ++i)
	{
		auto LocalGraph = Cast<AGraphAsset>(Actors[i]);
		LocalGraph->Modify();
		LocalGraph->SetChunkIndex(i+1);
		auto DataAsset = LocalGraph->GetGraph();
		UGraphDataAsset* AssetObj = nullptr;
		if (DataAsset.IsNull())
		{
			FString AssetName = "DA_"+LocalGraph->GetName() + "_GraphData";
			FString AssetPath = GetDefault<USimulationSystemSettings>()->GraphDataPath;
			IAssetTools& Tools = FAssetToolsModule::GetModule().Get();
			
			UDataAssetFactory* Factory = NewObject<UDataAssetFactory>();

			AssetObj = Cast<UGraphDataAsset>(Tools.CreateAsset(AssetName, AssetPath, UGraphDataAsset::StaticClass(), Factory));
			if (ensure(IsValid(AssetObj)))
			{
				LocalGraph->SetGraph(AssetObj);
			}
		} else
		{
			AssetObj = DataAsset.LoadSynchronous();
		}
		if (!ensure(IsValid(AssetObj)))
		{
			continue;
		}
		
		FGraphSerialized& Graph = AssetObj->Graph;
		FProfilesSerialized& Profiles = AssetObj->Profiles;
		RebuildSelectedLocalGraph(World, LocalGraph, Links, Graph, Profiles);

		UEditorAssetSubsystem* Subsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
		if (ensure(IsValid(Subsystem)))
		{
			Subsystem->SaveLoadedAsset(AssetObj, false);
		}

		ensure(LocalGraph->MarkPackageDirty());
		
		SlowTaskL1.EnterProgressFrame(80.0f/Actors.Num());
	}
	GlobalGraph->GetProfileIDsController()->ClearAllProfiles();
	
	DebugDrawGraphEditor();
}

void USimulationSystemEditorFunctionLibrary::FullRebuild()
{
	CleanUp();
	Delay([](){Build();}, 0.5f, 3);
}

void USimulationSystemEditorFunctionLibrary::SpawnRebuild()
{
	FScopedSlowTask SlowTaskL1(100.0f, NSLOCTEXT("SpawnBuild", "BuildSpawn", "Spawn building"));
	SlowTaskL1.MakeDialog();
	auto UnrealEditorSubsystem = GEditor->GetEditorSubsystem<UUnrealEditorSubsystem>();
	if (!ensure(UnrealEditorSubsystem))
	{
		return;
	}
	auto World = UnrealEditorSubsystem->GetEditorWorld();
	auto GlobalGraph = USimulationFunctionLibrary::GetGlobalGraph(World);
	GlobalGraph->LoadGraphLinks();
	
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphAsset::StaticClass(), Actors);
	for(int i = 0; i < Actors.Num(); ++i)
	{
		auto LocalGraph = Cast<AGraphAsset>(Actors[i]);
		LocalGraph->Modify();
		auto DataAsset = LocalGraph->GetGraph();
		if (!ensure(!DataAsset.IsNull()))
		{
			continue;
		}
		UGraphDataAsset* AssetObj = DataAsset.LoadSynchronous();
		if (!ensure(IsValid(AssetObj)))
		{
			continue;
		}
		
		FProfilesSerialized& Profiles = AssetObj->Profiles;
		Profiles.Objects.Empty();
		LocalGraph->LoadGraph();
		RebuildLocalGraphSpawn(World, LocalGraph, Profiles);
		LocalGraph->UnloadGraph();

		UEditorAssetSubsystem* Subsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
		if (ensure(IsValid(Subsystem)))
		{
			Subsystem->SaveLoadedAsset(AssetObj, false);
		}

		ensure(LocalGraph->MarkPackageDirty());
		
		SlowTaskL1.EnterProgressFrame(100.0f/Actors.Num());
	}
	GlobalGraph->GetProfileIDsController()->ClearAllProfiles();
}

void USimulationSystemEditorFunctionLibrary::DebugDrawGraphEditor()
{
	auto UnrealEditorSubsystem = GEditor->GetEditorSubsystem<UUnrealEditorSubsystem>();
	if (!ensure(UnrealEditorSubsystem))
	{
		return;
	}
	USimulationSystemDeveloperFunctionLibrary::DebugDrawGraph(
		UnrealEditorSubsystem->GetEditorWorld(),
		GetMutableDefault<USimulationSystemDeveloperSettings>()->ShowTime);
}

void USimulationSystemEditorFunctionLibrary::Delay(TFunction<void()> InLambda, float InMinimumSeconds,
	int32 InMinimumFrames)
{
	auto Delay = NewObject<UAsyncEditorDelay>();
	auto Helper = NewObject<UEditorToolRunHelper>();
	Helper->AddToRoot();
	Delay->AddToRoot();
	Helper->OnDelay = [Delay, InLambda]()
	{
		InLambda();
		Delay->RemoveFromRoot();
	};
	Delay->Complete.AddDynamic(Helper, &UEditorToolRunHelper::OnDelayComplete);
	Delay->Start(InMinimumSeconds, InMinimumFrames);
}
