// Fill out your copyright notice in the Description page of Project Settings.


#include "SimulationSystemEditorFunctionLibrary.h"

#include "DrawDebugHelpers.h"
#include "EditorLevelLibrary.h"
#include "EditorLevelUtils.h"
//#include "ExposedFunctionLibrary.h"
#include "GlobalGraph.h"
#include "GraphAsset.h"
#include "ProfileComponent.h"
#include "ProfileIDController.h"
#include "SimActorInterface.h"
#include "SimProfileBase.h"
#include "SimulationFunctionLibrary.h"
#include "SimulationSystemDeveloperFunctionLibrary.h"
#include "SimulationSystemDeveloperSettings.h"
#include "Graph/GraphPointManual.h"
#include "Graph/GraphGenerationRestrictor.h"
#include "Graph/GraphPointAutogenerated.h"
#include "Graph/GraphPointLink.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Misc/ScopedSlowTask.h"
#include "SimProfileContainer.h"
#include "EditorSimActor.h"
#include "Serialization/ObjectAndNameAsStringProxyArchive.h"

void USimulationSystemEditorFunctionLibrary::RebuildSelectedLocalGraph(UWorld* World,
                                                                       AGraphAsset* LocalGraph,
                                                                       const TMap<AGraphPointLink*,
                                                                                  TSharedPtr<Simulation::Vertex>>& Links,
                                                                       FGraphSerialized& ReturnGraph,
                                                                       FProfilesSerialized& ReturnProfiles)
{
	FScopedSlowTask SlowTaskL2(100.0f, NSLOCTEXT("SpawnBuild", "LocalGraphBuild", "Build local graph"));
	SlowTaskL2.MakeDialog();	
	FVector ZoneLocation = LocalGraph->GetActorLocation();
	FVector ZoneSize = LocalGraph->GetZoneSize();
	TArray<FHitResult> OutHits;
	FCollisionQueryParams Params;
	Params.bDebugQuery = true;
	UKismetSystemLibrary::LineTraceMulti(World,
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneSize.Z-ZoneLocation.Z),
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneLocation.Z-ZoneSize.Z),
		UEngineTypes::ConvertToTraceType(GetMutableDefault<USimulationSystemDeveloperSettings>()->SimPointsTraceChannel),
		true, {}, EDrawDebugTrace::Persistent, OutHits, false);
	/*World->LineTraceMultiByChannel(
		OutHits,
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneSize.Z-ZoneLocation.Z),
		FVector(ZoneLocation.X, ZoneLocation.Y, ZoneLocation.Z-ZoneSize.Z),
		GetMutableDefault<USimulationSystemDeveloperSettings>()->SimPointsTraceChannel,
		Params
	);*/
	TArray<FName> Layers = {};
	for(auto& Hit : OutHits)
	{
		Layers.AddUnique(
			GetLayerName(Hit.GetActor())
			);
		SlowTaskL2.EnterProgressFrame(10.0f/OutHits.Num());
	}
	TMap<AGraphPointLink*, TSharedPtr<Simulation::Vertex>> RequiredLinks;
	for(auto& Link : Links)
	{
		if(Link.Key->ConnectsChunk(LocalGraph))
		{
			RequiredLinks.Add(Link);
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Links.Num());
	}
	TArray<AGraphGenerationRestrictor*> Restrictors;
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphGenerationRestrictor::StaticClass(), Actors);
	for(auto& Actor : Actors)
	{
		if(Layers.Contains(GetLayerName(Actor)))
		{
			Restrictors.Add(Cast<AGraphGenerationRestrictor>(Actor));
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Actors.Num());
	}
	TArray<AGraphPointManual*> ManualPoints;
	Actors.Empty();
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointManual::StaticClass(), Actors);
	for(auto& Actor : Actors)
	{
		if(UKismetMathLibrary::IsPointInBox(Actor->GetActorLocation(), ZoneLocation, ZoneSize))
		{
			ManualPoints.Add(Cast<AGraphPointManual>(Actor));
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Actors.Num());
	}
	struct PointsArr
	{
		TArray<FVector> FoundPoints = {};
	};
	TMap<FName, PointsArr> FoundPointsPerLayer;
	TArray<FVector> FoundPointsXY = {};
	//TArray<FVector> ProcessedPoints = {ZoneLocation+FVector(0.0f, 0.0f, 100.0f)};
	TArray<FVector> ProcessedPoints = {ZoneLocation};
	float MinDistanceSq = GetMutableDefault<USimulationSystemDeveloperSettings>()->MinimumDistance
				*GetMutableDefault<USimulationSystemDeveloperSettings>()->MinimumDistance;
	while(ProcessedPoints.Num())
	{
		FScopedSlowTask SlowTaskL3(100.0f, FText::Format(NSLOCTEXT("SpawnBuild", "ProcessPointLocation", "Found points/Locations left: %d/%d"), FoundPointsXY.Num(), ProcessedPoints.Num()));
		SlowTaskL3.MakeDialog();
		FVector Point = ProcessedPoints.Pop();
		if(!UKismetMathLibrary::IsPointInBox(Point, ZoneLocation, ZoneSize))
		{
			continue;
		}
		bool RejectPoint = false;
		for(auto& FoundPoint :FoundPointsXY)
		{
			if(FVector::DistSquared2D(Point, FoundPoint) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		for(auto& SpawnedPoint : ManualPoints)
		{
			if(FVector::DistSquared(Point, SpawnedPoint->GetActorLocation()) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		for(auto& SpawnedPoint : RequiredLinks)
		{
			if(FVector::DistSquared(Point, SpawnedPoint.Key->GetActorLocation()) < MinDistanceSq)
			{
				RejectPoint = true;
				break;
			}
		}
		if(RejectPoint)
		{
			continue;
		}
		OutHits.Empty();
		World->LineTraceMultiByChannel(
			OutHits,
			FVector(Point.X, Point.Y, ZoneSize.Z-Point.Z),
			FVector(Point.X, Point.Y, Point.Z-ZoneSize.Z),
			
			GetMutableDefault<USimulationSystemDeveloperSettings>()->SimPointsTraceChannel
		);
		FoundPointsXY.Add(FVector(Point.X, Point.Y, 0.0f));
		for(auto& Hit : OutHits)
		{
			FName HitLayer = GetLayerName(Hit.GetActor());
			if(!FoundPointsPerLayer.Contains(HitLayer))
			{
				FoundPointsPerLayer.Add(HitLayer);
			}
			TArray<FVector>& ArrToAdd = FoundPointsPerLayer[HitLayer].FoundPoints;
			for(auto& AlreadyAddedPoint : ArrToAdd)
			{
				if(FVector::DistSquared(Hit.Location, AlreadyAddedPoint) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(!RejectPoint)
			{
				ArrToAdd.Add(Hit.Location+FVector(0.0f, 0.0f, GetMutableDefault<USimulationSystemDeveloperSettings>()->PointZOffset));
			}
		}
		for(int i = 0; i < 6; ++i)
		{
			RejectPoint = false;
			FVector ModifiedPoint = Point
				+UKismetMathLibrary::RotateAngleAxis(
					FVector::ForwardVector,
					i*60.0f,
					FVector::UpVector)
				*GetMutableDefault<USimulationSystemDeveloperSettings>()->DefaultDistance;
			for(auto& AlreadyAddedPoint : FoundPointsXY)
			{
				if(FVector::DistSquared(ModifiedPoint, AlreadyAddedPoint) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			ProcessedPoints.Add(ModifiedPoint);
			//FoundPointsXY.Add(ModifiedPoint);
		}
	}
	SlowTaskL2.EnterProgressFrame(20.0f);
	int Index;
	//using LevelGraph = TPair<TArray<TSharedPtr<Simulation::Vertex>>, TArray<TSharedPtr<Simulation::Edge>>>;
	TArray<LevelGraph> ChunkGraphs;
	//ChunkGraphs.Reserve(Layers.Num());
	ChunkGraphs.Init(LevelGraph(), Layers.Num());
	for(auto& Pair : FoundPointsPerLayer)
	{
		Index = 0;
		Actors.Empty();
		FScopedSlowTask SlowTaskL3(100.0f, NSLOCTEXT("SpawnBuild", "CreateGraphPoints", "Create graph points"));
		SlowTaskL3.MakeDialog();
		for(auto& Point : Pair.Value.FoundPoints)
		{
			bool RejectPoint = false;
			for(auto& Restrictor : Restrictors)
			{
				if(GetLayerName(Restrictor)==Pair.Key && Restrictor->IsPointInside(Point))
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			for(auto& LinkPoint : RequiredLinks)
			{
				if(FVector::DistSquared(Point, LinkPoint.Key->GetActorLocation()) < MinDistanceSq)
				{
					RejectPoint = true;
					break;
				}
			}
			if(RejectPoint)
			{
				continue;
			}
			FSimVertexID NewID;
			NewID.ChunkID = LocalGraph->GetChunkIndex();
			ensure(Layers.Contains(Pair.Key));
			if (Layers.Contains(Pair.Key))
			{
				NewID.LevelID = Layers.Find(Pair.Key);
				NewID.VertexID = Index++;
				auto GraphPoint = Cast<AGraphPointAutogenerated>(UEditorLevelLibrary::SpawnActorFromClass(AGraphPointAutogenerated::StaticClass(), Point));
				GraphPoint->SetVertexID(NewID);
				Actors.Add(GraphPoint);
				auto& Arr = ChunkGraphs[NewID.LevelID].Key;
				Arr.Add(MakeShared<Simulation::Vertex>(NewID, Point));
				SlowTaskL3.EnterProgressFrame(100.0f/Pair.Value.FoundPoints.Num());
			}
		}
		UEditorLevelUtils::MoveActorsToLevel(Actors, UGameplayStatics::GetStreamingLevel(World, Pair.Key));
		SlowTaskL2.EnterProgressFrame(10.0f/FoundPointsPerLayer.Num());
	}
	float MaxDistance = GetMutableDefault<USimulationSystemDeveloperSettings>()->MaximumDistance;
	for(int i = 0; i < Layers.Num(); ++i)
	{
		FScopedSlowTask SlowTaskL3(ChunkGraphs[i].Key.Num(), FText::Format(NSLOCTEXT("SpawnBuild", "ProcessEdgeCreation", "Process vertices from layer {0}"), FText::FromName(Layers[i])));
		SlowTaskL3.MakeDialog();
		for(int L1 = 0; L1 < ChunkGraphs[i].Key.Num(); ++L1)
		{
			for(int L2 = L1+1; L2 < ChunkGraphs[i].Key.Num(); ++L2)
			{
				auto& VertexOne = ChunkGraphs[i].Key[L1];
				auto& VertexTwo = ChunkGraphs[i].Key[L2];
				if(FVector::DistSquared(VertexOne->GetLocation(), VertexTwo->GetLocation()) > MaxDistance*MaxDistance)
				{
					continue;
				}
				ChunkGraphs[i].Value.Add(MakeShared<Simulation::Edge>(VertexOne, VertexTwo));
				VertexOne->AddEdge(ChunkGraphs[i].Value.Last());
				VertexTwo->AddEdge(ChunkGraphs[i].Value.Last());
			}
			SlowTaskL3.EnterProgressFrame(1);
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Layers.Num());
	}
	{
		FScopedSlowTask SlowTaskL3(RequiredLinks.Num(), NSLOCTEXT("SpawnBuild", "ProcessEdgeCreation", "Process link vertices"));
		SlowTaskL3.MakeDialog();
		for(auto& LinkPoint : RequiredLinks)
		{
			auto& LinkVertex = LinkPoint.Value;
			for(int i = 0; i < Layers.Num(); ++i)
			{
				for(auto& Vertex : ChunkGraphs[i].Key)
				{
					if(FVector::DistSquared(Vertex->GetLocation(), LinkVertex->GetLocation()) > MaxDistance*MaxDistance)
					{
						continue;
					}
					ChunkGraphs[i].Value.Add(MakeShared<Simulation::Edge>(Vertex, LinkVertex));
					Vertex->AddEdge(ChunkGraphs[i].Value.Last());
					LinkVertex->AddEdge(ChunkGraphs[i].Value.Last());
				}
			}
			SlowTaskL3.EnterProgressFrame(1);
		}
		SlowTaskL2.EnterProgressFrame(10.0f);
	}
	Actors.Empty();
	TSet<AActor*> ActorsInsideChunk = {};
	UGameplayStatics::GetAllActorsWithInterface(World, USimActorInterface::StaticClass(), Actors);
	for(auto& Actor: Actors)
	{
		if(UKismetMathLibrary::IsPointInBox(Actor->GetActorLocation(), LocalGraph->GetActorLocation(), LocalGraph->GetZoneSize()))
		{
			ActorsInsideChunk.Add(Actor);
		}
	}
	for(int i = 0; i < Layers.Num(); ++i)
	{
		for(auto& Vertex : ChunkGraphs[i].Key)
		{
			ReturnGraph.Vertices.Add(Vertex->GetVertexID(), Vertex->GetLocation());
		}
		for(auto& Edge : ChunkGraphs[i].Value)
		{
			ReturnGraph.Edges.Add({Edge.Get()->GetVertexOne().Pin()->GetVertexID(), Edge.Get()->GetVertexTwo().Pin()->GetVertexID()});
		}
		/*for(auto& Actor : ActorsInsideChunk)
		{
			if(GetLayerName(Actor)!=Layers[i])
			{
				continue;
			}
			IEditorSimActor* Inter = Cast<IEditorSimActor>(Actor);
			Inter->DirectSetGraphVertex(GetClosestVertex(Actor->GetActorLocation(), ChunkGraphs, i).Pin()->GetVertexID());
			auto NewProfile = Inter->GetProfile();
			if(!NewProfile)
			{
				continue;
			}
			NewProfile->SetOnlineLocation(Actor->GetActorLocation());
			if(IsValid(NewProfile)){
				SaveProfile(
					NewProfile,
					ReturnProfiles,
					GetClosestVertex(Actor->GetActorLocation(), ChunkGraphs, i).Pin()->GetVertexID()
					);
			}
		}*/
		for(auto& Actor : ActorsInsideChunk)
		{
			if(GetLayerName(Actor)!=Layers[i])
			{
				continue;
			}
			FEditorScriptExecutionGuard ScriptGuard;
			if (ISimActorInterface::Execute_UseInSimulation(Actor))
			{
				auto Component = ISimActorInterface::Execute_GetProfileComponent(Actor);
				if (!IsValid(Component))
				{
					ISimActorInterface::Execute_DirectSetGraphVertex(
						Actor, GetClosestVertex(Actor->GetActorLocation(), ChunkGraphs, i).Pin()->GetVertexID());
				} else
				{
					SaveProfile(
						Component->InitProfile(),
						ReturnProfiles,
						GetClosestVertex(Actor->GetActorLocation(), ChunkGraphs, i).Pin()->GetVertexID()
						);
				}
			}
		}
		SlowTaskL2.EnterProgressFrame(10.0f/Layers.Num());
	}
}

FName USimulationSystemEditorFunctionLibrary::GetLayerName(UObject* Obj)
{
	FString Str;
	if(auto GraphPoint = Cast<AGraphPointLink>(Obj))
	{
		Str = GraphPoint->GetChunkName();
	} else
	{
		Str = UKismetSystemLibrary::GetObjectName(
			UKismetSystemLibrary::GetOuterObject(
				UKismetSystemLibrary::GetOuterObject(
					Obj
					)
				)
			);
	}
	return FName(Str);
}

bool USimulationSystemEditorFunctionLibrary::IsUniqueTriple(
	const TArray<TTuple<TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>>>& Trilpes,
	TTuple<TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>, TWeakPtr<Simulation::Edge>> NewTuple)
{
	for(auto& Triple : Trilpes)
	{
		TSet<TWeakPtr<Simulation::Edge>> EdgesSet = {};
		EdgesSet.Add(Triple.Get<0>());
		EdgesSet.Add(Triple.Get<1>());
		EdgesSet.Add(Triple.Get<2>());
		EdgesSet.Add(NewTuple.Get<0>());
		EdgesSet.Add(NewTuple.Get<1>());
		EdgesSet.Add(NewTuple.Get<2>());
		if(EdgesSet.Num() <=3)
		{
			return false;
		}
	}
	return true;
}

TWeakPtr<Simulation::Vertex> USimulationSystemEditorFunctionLibrary::GetClosestVertex(FVector Location, 
	const TArray<LevelGraph>& GraphPart, int LayerIndex)
{
	TWeakPtr<Simulation::Vertex> ClosestVertex = GraphPart[LayerIndex].Key[0];
	long double ClosestDistanceSq = FVector::DistSquared(Location, ClosestVertex.Pin()->GetLocation());
	bool FoundCloser;
	do
	{
		FoundCloser = false;
		auto NewCloser = ClosestVertex;
		for(auto& Edge : ClosestVertex.Pin()->GetEdges())
		{
			auto Opposite = Edge.Pin()->GetOpposite(ClosestVertex);
			float OppositeDistanceSq = FVector::DistSquared(Opposite.Pin()->GetLocation(), Location);
			if(OppositeDistanceSq < ClosestDistanceSq)
			{
				FoundCloser = true;
				ClosestDistanceSq = OppositeDistanceSq;
				NewCloser = Opposite;
			}
		}
		ClosestVertex = NewCloser;
	} while (FoundCloser);
	return ClosestVertex;
}

void USimulationSystemEditorFunctionLibrary::SaveProfile(USimProfileBase* Profile, FProfilesSerialized& ReturnProfiles,
	FSimVertexID VertexID)
{
	FSerializedProfile Serialized;
	Serialized.ObjectClass = Profile->GetClass();
	Serialized.VertexLocation = VertexID;
	USimulationFunctionLibrary::SaveObjectData(Profile, Serialized.ObjectData.SerializedObject);
	if(Profile->GetClass()->ImplementsInterface(USimProfileContainer::StaticClass()))
	{
		auto ChildProfiles = ISimProfileContainer::Execute_GetAllItems(Profile);
		Serialized.ChildrenNum = ChildProfiles.Num();
		ReturnProfiles.Objects.Add(Serialized);
		for(auto& Child : ChildProfiles)
		{
			SaveProfile(Child, ReturnProfiles);
		}
	} else
	{
		ReturnProfiles.Objects.Add(Serialized);
	}
}

void USimulationSystemEditorFunctionLibrary::FullRebuild()
{
	FScopedSlowTask SlowTaskL1(100.0f, NSLOCTEXT("SpawnBuild", "RebuildAll", "Full spawn rebuilding"));
	SlowTaskL1.MakeDialog();
	auto World = UEditorLevelLibrary::GetEditorWorld();
	auto GlobalGraph = USimulationFunctionLibrary::GetGlobalGraph(World);
	TArray<AActor*> Actors;
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointAutogenerated::StaticClass(), Actors);
	for(auto& Actor : Actors)
	{
		Actor->Destroy();
	}
	Actors.Empty();
	UGameplayStatics::GetAllActorsOfClass(World, AGraphPointLink::StaticClass(), Actors);
	SlowTaskL1.EnterProgressFrame(10.0f);
	GlobalGraph->ResetVertices();
	GlobalGraph->GetProfileIDsController()->ClearAllProfiles();
	TMap<AGraphPointLink*, TSharedPtr<Simulation::Vertex>> Links;
	for(uint16 i = 0; i < Actors.Num(); ++i)
	{
		auto CastedActor = Cast<AGraphPointLink>(Actors[i]);
		const auto& Vertex =  Links.Add(CastedActor, MakeShared<Simulation::Vertex>(FSimVertexID{0, 0, i}, CastedActor->GetActorLocation()));
		GlobalGraph->AddVertex(Vertex->GetVertexID(), Vertex->GetLocation());
		SlowTaskL1.EnterProgressFrame(10.0f/Actors.Num());
	}
	Actors.Empty();
	UGameplayStatics::GetAllActorsOfClass(World, AGraphAsset::StaticClass(), Actors);
	GlobalGraph->SetChunks(Actors);
	for(int i = 0; i < Actors.Num(); ++i)
	{
		auto LocalGraph = Cast<AGraphAsset>(Actors[i]);
		LocalGraph->SetChunkIndex(i+1);
		FGraphSerialized Graph;
		FProfilesSerialized Profiles;
		RebuildSelectedLocalGraph(World, LocalGraph, Links, Graph, Profiles);
		LocalGraph->SetGraph(Graph);
		LocalGraph->SetInitialProfiles(Profiles);
		SlowTaskL1.EnterProgressFrame(80.0f/Actors.Num());
	}
	GlobalGraph->GetProfileIDsController()->ClearAllProfiles();
	DebugDrawGraphEditor();
}

void USimulationSystemEditorFunctionLibrary::DebugDrawGraphEditor()
{
	USimulationSystemDeveloperFunctionLibrary::DebugDrawGraph(UEditorLevelLibrary::GetEditorWorld(), GetMutableDefault<USimulationSystemDeveloperSettings>()->ShowTime);
}
